### ISSUE TITLE
Alaska Court System logo issue in Personalized Action Plan

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#913]
The large AK court system logo is still showing up when printing or downloading PAPs.  (I hadn’t noticed before but when you get your PAP it says: “The information and resources below are from Legal Navigator’s partner organizations in Alaska” and then it shows the Alaska Court System logo.  It is not that easy to read.  Maybe it can have “Alaska Court System” written in text below or next to the logo??  This may be where it is coming from when you print your PAP.)  I’ve attached examples of what it looks like both when you try to print and download the PAP to the email in which I’m sending this list of items. 

 Shandan knows about the issue, at least when printing, and said they will fix it.

Issue submitted by Stacey Marz (AK)

**Comment by breeglej** [comment]
@KellyeDC - We should fix this.  Please use whatever Stacey wants to use (logo or text).

**Comment by KellyeDC-zz** [comment]
Logo is not viewable in the pdf download.

**Comment by KellyeDC-zz** [comment]
<img width="900" alt="Issue 913 Alaska logo" src="https://user-images.githubusercontent.com/45771252/59602131-03a32200-90d4-11e9-8e17-dd31cd5de792.PNG">

**Comment by KellyeDC-zz** [comment]
Ready for PO review.

**Comment by grawdon** [comment]
@KellyeDC The PAP did not have an Alaska Court logo at all. See example. Are they okay with this?
[Legal Navigator - https___dev.legalnav.org.pdf](https://github.com/LSCOIT/LegalNavigator/files/3297537/Legal.Navigator.-.https___dev.legalnav.org.pdf)

**Comment by KellyeDC-zz** [comment]
@grawdon The PAP on the screen displays the logo.  The download will be addressed in the next sprint to include the logo displaying on the download.  This is an issue with the current pdf creator.

**Comment by grawdon** [comment]
@KellyeDC I am not seeing any court logo on my PAP. See attached. 
[No Alaska court logo on PAP.pdf](https://github.com/LSCOIT/LegalNavigator/files/3346067/No.Alaska.court.logo.on.PAP.pdf)

**Comment by Olgaivchenko** [comment]
Done in Sprint 11. Move to Ready for Review

**Comment by grawdon** [comment]
@KellyeDC @yevhenobertas @asaperski-gloriumtech I have two PAPs saved and cannot get either to print or download, much less have a logo. This happens even when I uncheck one. If I remove one, I can download the remaining plan, but I can't print it and it doesn't have a logo.

**Comment by ozholob** [comment]
Hi @grawdon, fixed on dev
![image](https://user-images.githubusercontent.com/55988406/72420800-06f4ae00-3788-11ea-9ef3-ebdf9a1111cb.png)
![image](https://user-images.githubusercontent.com/55988406/72420815-0a883500-3788-11ea-96ae-3ed25244a9f4.png)

**Comment by grawdon** [comment]
@ozholob @KellyeDC  I still cannot print when I am in Chrome. I can download, but not print. I have made sure the pop up blocker has DEV as a safe site and my ad blocker is turned off.
