### ISSUE TITLE
Add page to support Child 2 Authoring - AK

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#956]
Create a new screen for authoring at Child 2 level (AK) - for Guided Assist 

I.e. Family/Divorce/ 10 stages/iterations of the divorce process 

See Attached

**Comment by KellyeDC-zz** [comment]
![image](https://user-images.githubusercontent.com/45771252/59387871-4a8dc200-8d38-11e9-97d2-d1c808302fe9.png)

**Comment by svasylenko** [comment]
@KellyeDC we have to talk about this task - I could not understand what we have to do

**Comment by KellyeDC-zz** [comment]
The intent of this user story is to insert a page between the Guided Assist search screen and the "It looks like you are searching for information..." page, to allow authors to develop content at the next level down (child 2).  

Let's discuss further if not clear.

**Comment by svasylenko** [comment]
GA search leads to page above, further state will provide GA to every topic shown there. If no such GA - this item in list should not be shown. After clocking on link above - Start Guided assist dialog (regular) to be shown.

**Comment by konstantin-orekhov** [comment]
08/01 - 8h

**Comment by konstantin-orekhov** [comment]
08/02 - 8h

**Comment by Olgaivchenko** [comment]
Done in dev environment.

**Comment by KellyeDC-zz** [comment]
Unable to test until the NLP API is updated from LUIS to Spot (and training).  Also, the Divorce json needs to be removed from the content db.

**Comment by KellyeDC-zz** [comment]
@svasylenko Is there anyway to review this functionality in STG or PROD?

**Comment by grawdon** [comment]
@KellyeDC I'm not sure what I'm looking for here. I read the whole thread and still don't understand. Can we discuss?

**Comment by grawdon** [comment]
@KellyeDC-zz I can't tell if this is working or not. I could not find a child 2 guided assist. I will reach out to Jeannie and Alex.
